version: 0.0
os: linux
files:
  - source: /www
    destination: /var/www/html/
permissions:
    - object: /var/www/html/assets
      owner: root
      mode: 777
      type:
        - directory
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
